-- MySQL Script generated by MySQL Workbench
-- Mon Aug 23 10:51:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LocaçãoArmário
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LocaçãoArmário
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LocaçãoArmário` DEFAULT CHARACTER SET utf8 ;
USE `LocaçãoArmário` ;

-- -----------------------------------------------------
-- Table `LocaçãoArmário`.`TB_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocaçãoArmário`.`TB_Pessoa` (
  `Código` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(120) NOT NULL,
  `Telefone` INT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LocaçãoArmário`.`TB_Armário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocaçãoArmário`.`TB_Armário` (
  `Código` INT NOT NULL AUTO_INCREMENT,
  `Tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LocaçãoArmário`.`TB_LocaçãoArmario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocaçãoArmário`.`TB_LocaçãoArmario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DataInício` DATE NOT NULL,
  `DataFim` DATE NOT NULL,
  `TB_Armário_Código` INT NOT NULL,
  `TB_Pessoa_Código` INT NOT NULL,
  INDEX `fk_TB_LocaçãoArmario_TB_Pessoa1_idx` (`TB_Pessoa_Código` ASC) VISIBLE,
  INDEX `fk_TB_LocaçãoArmario_TB_Armário1_idx` (`TB_Armário_Código` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TB_LocaçãoArmario_TB_Pessoa1`
    FOREIGN KEY (`TB_Pessoa_Código`)
    REFERENCES `LocaçãoArmário`.`TB_Pessoa` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_LocaçãoArmario_TB_Armário1`
    FOREIGN KEY (`TB_Armário_Código`)
    REFERENCES `LocaçãoArmário`.`TB_Armário` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
